Rewrite "get_stats()" so that it relies on "flock" to control concurr…
anapsix/zabbix-haproxy pull request #35
Opened 2017-01-30 18:45 UTC by amg1127

Sometimes, while monitoring a HAPROXY installation of mine, Zabbix triggers messages like this:

> Item value: grep: /var/run/zabbix/haproxy_stats.cache: No such file or directory
ERROR: bad haproxy-backend/BACKEND

> Trigger expression: {hostname.domain.com:haproxy.stats[{$HAPROXY_SOCK},haproxy-backend,BACKEND,status].iregexp("^up$",#1)}=0

I figured that the current "get_stats()" implementation may trigger a race condition if multiple backends are being monitored. For example:
1. Zabbix queries information about backend "A".
2. The "get_stats()" function on the monitored server verifies that the cache file is not too old.
3. Zabbix queries information about backend "B".
4. The "get_stats()" function on the monitored server verifies that the cache file is old and deletes it.
5. The processor context on the monitored server switches to (2)
6. The "get()" function tries to open a nonexistent file, because it was deleted by another process on step (4)
5. The processor context on the monitored server switches to (4) and the cache file is recreated.

I rewrote the "get_stats()" function so that it relies on the "[flock](https://linux.die.net/man/1/flock)" executable, from the "util-linux" package. In my implementation, "get()" obtains a shared lock before reading cached HAPROXY information and "get_stats()" obtains an exclusive lock before updating the cache.

2017-02-01 16:10 UTC, anapsix requested changes
great job on flock!..
got few comments and questions for you, when you get a chance

2017-02-01 16:10 UTC, anapsix commented on haproxy_stats.sh
> +  local _res="$("${FLOCK_BIN}" --shared --wait "${FLOCK_WAIT}" "${CACHE_STATS_FILEPATH}${FLOCK_SUFFIX}" grep $1 "${CACHE_STATS_FILEPATH}")"
do we need all the extra double-quotes here?
`_res="$(${FLOCK_BIN} --shared --wait ${FLOCK_WAIT} ${CACHE_STATS_FILEPATH}${FLOCK_SUFFIX} grep $1 ${CACHE_STATS_FILEPATH})"`

2017-02-01 16:10 UTC, anapsix commented on haproxy_stats.sh
> +debug "FLOCK_BIN           => $FLOCK_BIN"
please remove few extra spaces to alight with others

2017-02-01 16:10 UTC, anapsix commented on haproxy_stats.sh
> +  check_cache 'stat' "${CACHE_STATS_FILEPATH}" ${CACHE_STATS_EXPIRATION}
do we need the extra quotes here?

2017-02-01 16:10 UTC, anapsix commented on haproxy_stats.sh
> +  fi 200> "${cache_filepath}${FLOCK_SUFFIX}"
is 200 a file descriptor here?

2017-02-01 16:10 UTC, anapsix commented on haproxy_stats.sh
> +FLOCK_WAIT=300
should FLOCK_WAIT value be based on CACHE_STATS_EXPIRATION?
.. please comment the units of "FLOCK_WAIT"

2017-02-01 16:10 UTC, anapsix commented on haproxy_stats.sh
> +debug "FLOCK_BIN           => $FLOCK_BIN"
please add FLOCK_WAIT variable to debug, with units

2017-02-01 16:10 UTC, anapsix commented on haproxy_stats.sh
> +  if "${FLOCK_BIN}" --exclusive --wait "${FLOCK_WAIT}" 200
is 200 here meant to be a file descriptor? I assume it's related to line 202, but how does that work?

2017-02-01 16:10 UTC, anapsix commented on haproxy_stats.sh
> +  if "${FLOCK_BIN}" --shared --wait "${FLOCK_WAIT}" 200
is there a point of getting a shared lock here at all?
why not just check if the file is fresh enough or not first..
```
cache_filemtime=$(stat -c '%Y' "${cache_filepath}" 2> /dev/null)
  if [ $((cache_filemtime+60*cache_expiration)) -ge ${CUR_TIMESTAMP} ]
  then
  debug "${cache_type} file found, results are at most ${cache_expiration} minutes stale.."
    return 0
  elif ( ${FLOCK_BIN} --exclusive --wait ${FLOCK_WAIT} 200 )
  then
  [... continues from line 194 to 202 ... ]
```


```

2017-02-06 10:13 UTC, amg1127 commented on haproxy_stats.sh
> +FLOCK_WAIT=300
I believe it shouldn't. The FLOCK_WAIT variable governs the file locking behavior exclusively and is not related to any cache expiration handling. The meaning of the variable is the maximum number of seconds the "flock" binary should wait before giving up acquiring a lock. "flock" waits indefinitely for the lock by default.

For example, if FLOCK_WAIT==10 and HAPROXY daemon hangs, the cache writer process will be holding an exclusive lock and all reader processes will wait for up to 10 seconds before giving up acquiring shared locks.

---------------

Actually, I should comment the units and reduce the timeout value to 15 seconds too, because the maximum allowed timeout for commands executed by Zabbix agent is 30 seconds. In addition, the default timeout is 3 seconds ([reference](https://www.zabbix.com/documentation/2.4/manual/appendix/config/zabbix_agentd)). The current value doesn't have any effect.

2017-02-06 10:13 UTC, amg1127 commented on haproxy_stats.sh
> +debug "FLOCK_BIN           => $FLOCK_BIN"
I am going to do it.

2017-02-06 10:13 UTC, amg1127 commented on haproxy_stats.sh
> +debug "FLOCK_BIN           => $FLOCK_BIN"
I am going to do it.

2017-02-06 10:13 UTC, amg1127 commented on haproxy_stats.sh
> +  if "${FLOCK_BIN}" --shared --wait "${FLOCK_WAIT}" 200
I agree with you. The shared lock is actually needed in the "get()" function only. If a writer process updates the cache file between execution of "get_stats()" and "get()", the shared lock held there ensures the reader process access valid data.

I am going to remove the shared lock acquisition from here.

2017-02-06 10:13 UTC, amg1127 commented on haproxy_stats.sh
> +  if "${FLOCK_BIN}" --exclusive --wait "${FLOCK_WAIT}" 200
Yes, it is. 200 is the file descriptor for the file "/var/tmp/haproxy_stats.cache.lock" (for example), which is opened for writing by "bash". Actually, only line 192 is related to line 202; the line 191 is related to line 183 above.

-----

The "flock" binary doesn't use file paths to manage locks; it uses file descriptors instead. For example:

```
1.    # These commands are not protected by the lock
2.    echo I am $$ . Current date is $(date)
3.    (
4.        flock --exclusive 9
5.        # These commands will be executed under lock ...
6.        echo Again... I am $$ . Current date is $(date) 
7.        sleep 60
8.    ) 9>/var/lock/mylockfile
9.    echo Goodbye 
```

Let us suppose you run the code above. The following sequence of events happens:
- Line 2: The PID and the datetime are printed
- Line 3: Bash opens "/var/lock/mylockfile" for writing, using file descriptor number 9
- Line 4: Through the "fork()" system call, the "flock" process receives the opened file descriptor 9 and acquires an exclusive lock on it using the "flock()" system call. After it succeeds, the PID and the datetime are printed again (line 6) and the script sleeps for 1 minute (line 7)
- Line 8: Bash closes the file descriptor number 9
- Line 9: The message is printed and the script exits

See [flock(2)](https://linux.die.net/man/2/flock) man page for more information regarding how it works. [flock(1)](https://linux.die.net/man/1/flock) command is just a wrapper to it. I also suggest you to run 2 instances of that code concurrently and see the outputs.

2017-02-06 10:13 UTC, amg1127 commented on haproxy_stats.sh
> +  fi 200> "${cache_filepath}${FLOCK_SUFFIX}"
Yes, it it. See previous comment.

2017-02-06 10:13 UTC, amg1127 commented on haproxy_stats.sh
> +  check_cache 'stat' "${CACHE_STATS_FILEPATH}" ${CACHE_STATS_EXPIRATION}
Well... The extra quotes are not necessary at all. It only makes difference if there are spaces in the path, which is rarely used.

However, I believe extra quoting would prevent [the famous bumblebee bug #123](https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/issues/123) from happening. This is why I usually quote variables in my scripts. It is a kind of "better safe than sorry" behavior.

2017-02-06 10:13 UTC, amg1127 commented on haproxy_stats.sh
> +  local _res="$("${FLOCK_BIN}" --shared --wait "${FLOCK_WAIT}" "${CACHE_STATS_FILEPATH}${FLOCK_SUFFIX}" grep $1 "${CACHE_STATS_FILEPATH}")"
See previous comment.

2017-02-14 05:50 UTC, anapsix approved these changes
lgtm

2017-02-14 05:50 UTC, merged